#ifndef AGPS_H
#define AGPS_H

#include <stdint.h>

#define TX_PACKET_SIZE      6
#define RX_PACKET_SIZE      5

#define COMMAND_SYSTEM              0x00
#define COMMAND_READ_REGISTER       0x01
#define COMMAND_WRITE_REGISTER      0x02
#define COMMAND_READ_PARAMETER      0x03
#define COMMAND_WRITE_PARAMETER     0x04
#define COMMAND_CONTROL             0x05

#define REPLY_SYS_COMMAND_OK      0x00
#define REPLY_READ_REGISTER_OK    0x01
#define REPLY_WRITE_REGISTER_OK   0x02
#define REPLY_READ_PARAMETER_OK   0x03
#define REPLY_WRITE_PARAMETER_OK  0x04
#define REPLY_CONTROL_OK          0x05
#define REPLY_SYS_COMMAND_ERROR   0x06
#define REPLY_INPUT_TYPE_ERROR    0x07
#define REPLY_PACKET_SIZE_ERROR   0x08
#define REPLY_ADDRESS_RANGE_ERROR 0x09
#define REPLY_PERMISSION_ERROR    0x0A
#define REPLY_CONTROL_ERROR       0x0B

#endif
